#!/usr/bin/env python

import sys
from bundle_lib import get_topologies

def main():
    which = sys.argv[1]
    riak_topo, rcs_topo = get_topologies()
    if which == "riak":
        print(max([max(nn) for nn in riak_topo.values()]))
    elif which == "rcs":
        print(len(rcs_topo))
    elif which == "stanchion" or which == "rcsc":
        print(len(riak_topo))


if __name__ == "__main__":
    main()
