version: "3.9"
services:

  riak:
    ports:
      - "8087:8087"
      - "8098:8098"
      - "9080:9080"
    build:
      dockerfile: ${RIAK_DOCKERFILE}
      context: .
    image: "rcs_bundle_riak.${RIAK_VSN}"

  stanchion:
    ports:
      - "8085:8085"
    build:
      dockerfile: ${STANCHION_DOCKERFILE}
      context: .
    image: "rcs_bundle_stanchion.${STANCHION_VSN}"

  riak_cs:
    ports:
      - "8080:8080"
      - "8000:8000"
    build:
      dockerfile: ${RCS_DOCKERFILE}
      context: .
    image: "rcs_bundle_riak_cs.${RCS_VSN}"

  riak_cs_control:
    ports:
      - "8090:8090"
    build:
      dockerfile: ${RCSC_DOCKERFILE}
      context: .
    image: "rcs_bundle_riak_cs_control.${RCSC_VSN}"
