#!/bin/env python

# Copyright (c) 2021-2023 TI Tokyo. All Rights Reserved.
#
# This file is provided to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain
# a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# ---------------------------------------------------------------------

# Helper script to read topology files and return the number of nodes
# of each kind. Part of riak_cs_service_bundle.


import sys
from bundle_lib import get_topologies

def main():
    which = sys.argv[1]
    riak_topo, rcs_topo = get_topologies()
    if which == "riak":
        print(max([max(nn) for nn in riak_topo.values()]))
    elif which == "rcs":
        print(len(rcs_topo))
    elif which == "stanchion" or which == "rcsc":
        print(len(riak_topo))


if __name__ == "__main__":
    main()
